sudo: false
language: ruby
before_install:
  - gem install bundler -v 1.15.3

rvm:
  - "2.4"
  - "2.3"
  - "2.2.2"
  - "ruby-head"
  - "jruby"
  - "jruby-head"

gemfile:
  - gemfiles/Rails-5.1.gemfile

matrix:
  include:
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-head.gemfile"
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-5.0.gemfile"
    - rvm: "2.3"
      gemfile: "gemfiles/Rails-4.2.gemfile"
    - rvm: "2.3"
      gemfile: "gemfiles/Rails-4.1.gemfile"
    - rvm: "2.3"
      gemfile: "gemfiles/Rails-4.0.gemfile"

  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
    - rvm: "jruby"
    - gemfile: "gemfiles/Rails-head.gemfile"
